export const FETCH_MOVIES_LOADING = 'FETCH_MOVIES_LOADING';
export const ADD_FETCHED_MOVIES = 'ADD_FETCHED_MOVIES';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';
export const SELECTED_MOVIE = 'SELECTED_MOVIE';
export const SET_PAGE = 'SET_PAGE';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';
export const HANDLE_MODAL = 'HANDLE_MODAL';